version: 2.1

jobs:
  build:
    docker:
      - image: node:16-alpine3.14
        user: node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build application
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - "dist"

  deploy-gh-pages:
    docker:
      - image: node:16-alpine3.14
        user: node
    steps:
      - attach_workspace:
          at: dist
      - run: pwd
      - run: ls
      - run:
          name: Install and configure dependencies
          command: npm install -g --silent gh-pages
      - run:
          name: Deploy to gh-pages branch
          command: gh-pages --dist dist

workflows:
  deploy-gh-pages:
    jobs:
      - build
      - deploy-gh-pages
