version: 2.1

jobs:
  build:
    docker:
      - image: node:16-alpine3.14
        user: node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build application
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - "dist"

  deploy-gh-pages:
    docker:
      - image: node:16-alpine3.14
    steps:
      - attach_workspace:
          at: dist
      - checkout
      - run: npm init -y
      - run: npm i -D gh-pages
      - run: git config user.email "19966190+paulbarre@users.noreply.github.com"
      - run: git config user.name "Paul Barré"
      - run:
          name: Deploy to gh-pages branch
          command: npx gh-pages --dist dist

workflows:
  deploy-gh-pages:
    jobs:
      - build
      - deploy-gh-pages:
          requires:
            - build
