version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: node:16
        user: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          paths:
            - "node_modules"
          key: dependencies
      - run:
          name: Build application
          command: npm run build
      - run: npm i -D gh-pages
      - run: git config user.email "19966190+paulbarre@users.noreply.github.com"
      - run: git config user.name "Paul Barré"
      - run:
          name: Deploy to gh-pages branch
          command: npx gh-pages --dist dist

workflows:
  deploy-gh-pages:
    jobs:
      - build-and-deploy